apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
type: Opaque
stringData:
  RESEND_API_KEY: "insert_resend_key_here"
  SLACK_WEBHOOK_URL: "insert_slack_webhook_here"
  INCIDENT_ROUTING_KEY: "insert_pagerduty_key_here"

